# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='LGPL'
logoFile="logo.png"
[[mods]]
modId="secretly_complicated"
version="${file.jarVersion}"
displayName="Secretly Complicated"
credits="SecretlyComplicated Contributors, SecretAsain, and the Not Too Complicated Community"
authors="Liz Fransen"
description='''
A mod for not too complicated 3
'''
[[dependencies.secretly_complicated]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.secretly_complicated]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
